language: cpp
sudo: false

matrix:
  include:
    #============================================================
    #
    #             Debug 
    #
    #============================================================
    #==============================
    #
    #     linux g++ 
    #
    #==============================
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    #==============================
    #
    #     linux clang++ 
    #
    #==============================

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    #============================================================
    #
    #             Release 
    #
    #============================================================
    #==============================
    #
    #     linux g++ 
    #
    #==============================
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    #==============================
    #
    #     linux clang++ 
    #
    #==============================

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

before_install:
  - eval

before_script:
  - cd ${TRAVIS_BUILD_DIR}/..  
  - mkdir build
  - cd build
  - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CC_COMPILER=${CC}

script:
  - make